on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      -
        name: Prepare coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && \
          chmod +x ./cc-test-reporter && \
          ./cc-test-reporter before-build && \
          go get -u github.com/jandelgado/gcov2lcov
      -
        name: Run tests
        run: |
          go test -v ./... -coverprofile=coverage.out -covermode=atomic && \
          mkdir -p coverage && \
          gcov2lcov -infile=coverage.out -outfile=coverage/lcov.info
      -
        name: Push coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        run: |
          ./cc-test-reporter after-build -t lcov
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: natx
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: natx/synthetic:${{ steps.tag_name.outputs.SOURCE_TAG }}
