on: [pull_request]

env:
  GO_VERSION: '^1.21'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run tests
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        run: |
          scripts/check.sh all
  check-license:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Check license file is present
        run: |
          find . -name LICENSE.md
