on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      -
        name: Run tests
        run: go test -v ./...
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: natx
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: natx/synthetic:latest
